languageCode: en-us
title: dead airspace
theme: PaperMod
disqusShortname: dead-airspace

params:
  env: production
  images: ["/imgs/dead-airspace.png"]
  comments: true
  ShowReadingTime: true
  ShowShareButtons: true

  assets:
    favicon: /favicons/favicon.ico
    favicon16x16: /favicons/favicon-16x16.png
    favicon32x32: /favicons/favicon-32x32.png
    apple_touch_icon: /favicons/apple-touch-icon.png

  cover:
    linkFullImages: true
    responsiveImages: true

  label:
    text: "dead-airspace"
    icon: /favicons/icon.svg
    iconHeight: 35

  homeInfoParams:
    Title: Greetings. Traveller.
    Content: "This is dharmx, your operator. Be advised, you have entered dead-airspace,
             a feedback loop of corrupt transmissions. This signal is being broadcasted from
             an abandoned space station. Traversing aimlessly through dead-space recording
             and archiving its findings. Hope you find these recordings useful if not, entertaining."

  profileMode:
    enabled: true
    title: "Greetings. Visitor."
    subtitle: "This is dharmx, your operator. Be advised, you have entered dead-airspace,
              a feedback loop of corrupt transmissions."
    imageUrl: "/imgs/profile.png"
    imageTitle: "Hello."
    imageWidth: 120
    imageHeight: 120
    buttons:
      - name: Github
        url: "https://github.com/dharmx"

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 2
    keys: ["title", "permalink", "summary", "content", "journals", "eww"]

menu:
  main:
    - identifier: journals
      name: Journals
      url: /journals/
      weight: 10
    - name: Search
      url: /search/
      weight: 20
    - identifier: archives
      name: Categories
      url: /categories/
      weight: 30
    - name: Tags
      url: /tags/
      weight: 40

minify:
  disableXML: true
  minifyOutput: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    noclasses: false
  tableOfContents:
    ordered: true
