baseURL: https://dharmx.github.io/dharmx
languageCode: en-us
title: Dharma
theme: PaperMod

params:
  cover:
    linkFullImages: true
    responsiveImages: true

  ShowBreadCrumbs: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: false
  ShareButtons: ["linkedin", "twitter"]

  profileMode:
    enabled: false
    title: Dharmx
    subtitle: Your Mother.
    imageUrl: images/profile.png
    imageTitle: city
    imageWidth: 120
    imageHeight: 120
    buttons:
      - name: Archive
        url: "/archive"
      - name: Github
        url: "https://github.com/"

  socialIcons:
    - name: GitHub
      url: https://github.com/dharmx
    - name: Mail
      url: mailto:dharmx.dev@gmail.com
    - name: Discord
      url: https://discord.gg/CYX2nP22

  homeInfoParams:
    Title: Hi there wave
    Content: Can be Info, links, about...

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
