baseURL = ""
theme = "DoIt"
themesDir = "themes"
title = "dead airspace"
defaultContentLanguage = "en"
languageCode = "en"
languageName = "English"
hasCJKLanguage = false
paginate = 12
googleAnalytics = ""
copyright = ""
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = false
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

[author]
  name = "dharmx"
  email = "dharmx.dev@gmail.com"
  link = "https://dharmx.is-a.dev"

[menu]
  [[menu.main]]
    weight = 1
    identifier = "journals"
    pre = ""
    post = ""
    name = "Journals"
    url = "/posts/"
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
  [[menu.main]]
    weight = 4
    identifier = "github"
    pre = "<i class='fab fa-github fa-fw' aria-hidden='true'></i>"
    post = ""
    name = ""
    url = "https://github.com/dharmx/dharmx.github.io"
    title = "GitHub"

[params]
  defaultTheme = "auto"
  gitRepo = "https://github.com/dharmx/dharmx.github.io"
  fingerprint = ""
  dateFormat = "2006-01-02"
  title = "dead airspace"
  description = "A repository of my ramblings, findings and projects. Hope you find these useful in some way."
  images = ["/images/dead-airspace.png"]

  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
      logo = "/favicons/favicon.ico"
      name = "dead airspace"
      pre = ""
      post = ""
      typeit = true

  [params.footer]
    enable = true
    custom = ""
    hugo = false
    copyright = true
    author = true
    since = 2022
    icp = ""
    license = '<a rel="license external nofollow noopener noreffer" href="https://opensource.org/licenses/GPL-3.0" target="_blank">GPL-3.0</a>'

  [params.section]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

  [params.list]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

  [params.app]
    title = "dead airspace"
    noFavicon = false
    svgFavicon = "/favicons/favicon.ico"
    themeColor = "#ffffff"
    iconColor = "#5bbad5"
    tileColor = "#da532c"

  [params.search]
    enable = true
    type = "lunr"
    contentLength = 4000
    placeholder = "Query Database"
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"
    absoluteURL = false

  [params.home]
    rss = 10
    [params.home.profile]
      enable = true
      gravatarEmail = ""
      avatarURL = "/images/profile.png"
      title = "Greetings. Traveller."
      subtitle = "This is dharmx, your operator. Be advised, you have entered dead-airspace, a feedback loop of corrupt transmissions. This signal is being broadcasted from an abandoned space station. Traversing aimlessly through dead-space recording and archiving its findings. Hope you find these recordings useful if not, entertaining."
      typeit = true
      social = true
      disclaimer = "Tread Carefully."
    [params.home.posts]
      enable = true
      paginate = 6
  [params.social]
    GitHub = "dharmx"
    Gitlab = "pagankeymaster"
    Spotify = "0zghyzmplyhbpbam3p6p8koz3"
    Discord = "dharmx#2556"
    Email = "dharmx.dev@gmail.com"
    RSS = ""

  [params.page]
    hiddenFromHomePage = false
    hiddenFromSearch = false
    twemoji = true
    lightgallery = true
    ruby = true
    fraction = true
    fontawesome = true
    linkToMarkdown = true
    rssFullText = true
    [params.page.toc]
      enable = true
      keepStatic = false
      auto = true
    [params.page.code]
      copy = true
      maxShownLines = 50
    [params.page.math]
      enable = true
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      copyTex = true
      mhchem = true
    [params.page.mapbox]
      accessToken = "pk.eyJ1IjoiZGlsbG9uenEiLCJhIjoiY2s2czd2M2x3MDA0NjNmcGxmcjVrZmc2cyJ9.aSjv2BNuZUfARvxRYjSVZQ"
      lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
      darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
      navigation = true
      geolocate = true
      scale = true
      fullscreen = true
    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = true
      Whatsapp = true
      Pinterest = true
      Tumblr = true
      HackerNews = false
      Reddit = true
      Pocket = true
      Evernote = true
      Trello = true
    [params.page.comment]
      enable = true
      [params.page.comment.disqus]
        enable = true
        shortname = "dead-airspace"

  [params.typeit]
    speed = 100
    cursorSpeed = 1000
    cursorChar = "┃"
    duration = -1

  [params.seo]
    image = "/images/dead-airspace.png"
    thumbnailUrl = "/images/dead-airspace.png"

  [params.cookieconsent]
    enable = false
    [params.cookieconsent.content]
      message = ""
      dismiss = ""
      link = ""

  [params.cdn]
    data = "jsdelivr.yml"

  [params.compatibility]
    polyfill = true
    objectFit = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNumbersInTable = false
    noClasses = false
    anchorLineNos = false
    hl_inline = false
    lineNos = false
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = false
        title = true
      autoHeadingID = true
      autoHeadingIDType = "github"
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[Permalinks]
  posts = ":filename"

[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
